### ISSUE TITLE
Addon does not alter the page-width

### ISSUE THREAD

**Issue by PatrickWatzlawik** [ozymandias547/snaptest#1]
Hey guys,

The extension's window does not alter the page width. So things on the right side are not visible/interactable anymore. You'd have to change the alignment of the extension-window, perform your action, and revert the alignment settings.

![image](https://cloud.githubusercontent.com/assets/12525762/24606338/0be18dda-186d-11e7-8399-dc3fa298ae22.png)

It would be great, if the extension window acts like (for example) the dev-console docked on the right side.

Best regards,
Patrick

**Comment by ozymandias547** [comment]
Hi Patrick, totally agreed.  In the next couple of weeks we'll be adding options for the location of the extension - they will be "in tab", "window", and "dev tools".  

Until then, you'll have to minimize the extension (hotkey m) or dock it to the left to see what's under it.

**Comment by ozymandias547** [comment]
This has been fixed - SnapTest can now be a separate window or docked in devtools.
