### ISSUE TITLE
Feature Request: Multi-user for companies

### ISSUE THREAD

**Issue by VR-Architect** [ozymandias547/snaptest#13]
It would be great if a company could purchase a company license where all the tests are shared between the members of the QA Team. (aka a test "library"). Due to confidentiality issues, it would also be great if the shared test "library" was  permitted to be stored locally and not on the Internet.

**Comment by VR-Architect** [comment]
Oh, I just saw your plans web page and I see this is on your roadmap. Yah!!! Great product, I look forward to introducing the Teams version to the company for purchasing considerations.

**Comment by ozymandias547** [comment]
Great! It's currently about 50% done, and should be ready in about a month.
