### ISSUE TITLE
Feature Request: Local repository for tests

### ISSUE THREAD

**Issue by VR-Architect** [ozymandias547/snaptest#14]
Due to confidentiality and proprietary licensing of software being tested, it would be great if we could store  tests on a shared local file share. The Chrome client would have a setting to point to the repository. Some companies have very strict information security policies preventing the storage of information in the cloud.

**Comment by VR-Architect** [comment]
Thx. I signed up for the beta and went to Chrome Extensions but don't see a Private Mode setting. I see Allow Incognito and Allow Access to File URL.

**Comment by ozymandias547** [comment]
It's actually in the dropdown of the extension:

![image](https://user-images.githubusercontent.com/2013007/30718645-2a9ea848-9ee6-11e7-89ec-47839362bda3.png)

**Comment by VR-Architect** [comment]
Oh I see, sweet! 

Is there an easy button to move some tests from cloud to private? 
Also, please consider adding a button to open the local folder to where the private tests are stored.

**Comment by ozymandias547** [comment]
There is a button on the tests in the dashboard that allows you to move them to cloud.  Currently you have to do one by one, but on Monday I'll be releasing a "move all" feature that basically copies your entire cloud project to local.

**Comment by ozymandias547** [comment]
@VR-Architect "Move all" to private mode is complete.  you'll find it under the account section when you're in cloud mode.  Sorry if this is a bit late.
