### ISSUE TITLE
Feature Request: View Test Code for Folder

### ISSUE THREAD

**Issue by VR-Architect** [ozymandias547/snaptest#15]
For backup purposes, I would like to view or download a folder or project code to my local drive. Right now, I have to open each test, then copy paste to a file. Also as some of my actions (mouse-over to validate a menu popup) require a Selenium server, I am not quite sure how to get the code to the server.

**Comment by VR-Architect** [comment]
I discovered how to generate the code locally which meets this purpose. I recommend a link to the documentation be placed on the folder generation code page in the application to help other newbies :)

**Comment by ozymandias547** [comment]
Good idea.  It'll be in the release this Friday or Monday.  Thanks for the help on this.
