### ISSUE TITLE
Feature Request: Default Description for Page ready

### ISSUE THREAD

**Issue by VR-Architect** [ozymandias547/snaptest#17]
Could we get the description for action Page Ready to already have the description pre-populated with "Wait for page to load"? It would help speed up test creations.

**Comment by ozymandias547** [comment]
Interesting idea! It would have to be configurable in the options (default descriptions for actions) because we have a lot of international users.  I'll scope that out, but doesn't sound super complicated, and would save a lot of time/make tests nicer looking.

**Comment by ozymandias547** [comment]
@VR-Architect This will be ready to use in v0.6.0 coming out in a couple days.  Feel free to reopen if it doesn't suit your needs.
