### ISSUE TITLE
Folder drag and drop can go to Sample Test folder

### ISSUE THREAD

**Issue by VR-Architect** [ozymandias547/snaptest#18]
FYI, minor issue. Sometimes if you drag and drop a new folder it will not appear in the project I dropped it in. Instead it will appear in the Sample Tests folder. This also happened to me when dragging a test under a folder.

**Comment by ozymandias547** [comment]
Ah yea, I've seen this once in a blue moon.  We'll take a look again.

**Comment by VR-Architect** [comment]
I tried to recreate and I couldn't. I will be on the look out for you.

**Comment by ozymandias547** [comment]
Closing until we see it more often.

**Comment by karrla** [comment]
I've had this issue often with new Tests... It repeatable if the test is dragged above and below an expanded folder which has a number of tests in it. Once the new test is dragged above and then below the open folder it is hard to tell which folder the Test landed in.

![movingtest](https://user-images.githubusercontent.com/15875770/31444260-fea12994-ae9b-11e7-9d9f-948a752b98c5.gif)

**Comment by ozymandias547** [comment]
We are planning a directory rework.  Closing in lieu of that.
