### ISSUE TITLE
Feature Request: New assertion to detect font size

### ISSUE THREAD

**Issue by VR-Architect** [ozymandias547/snaptest#19]
We have a font enlarge and font reduce buttons on a website (https://lcec.net) and would like to assert that the fonts did change as expected. We could use the assert button to click some text on the page to check the font size against.

**Comment by VR-Architect** [comment]
If this is not possible, may a new manual pause task could be added where we give instructions to the tester? Then they put the results into the task to resume? Just an idea.

**Comment by ozymandias547** [comment]
A font-assertion would be cool.  Should be simple enough, so I'll try to get it in the release for tomorrow night - latest Monday.

As for the "pause and wait for manual action" feature, that is on the roadmap under "Manual mode prompts" [https://www.snaptest.io/product-roadmap](https://www.snaptest.io/product-roadmap).  It will be for any action that can't be played back in SnapTest (iframes mainly), but the font-size should be doable.

**Comment by ozymandias547** [comment]
@VR-Architect Check out the new "Style is" assertion in v0.5.2.  It can accomplish what you need.
