### ISSUE TITLE
Unable to perform the test

### ISSUE THREAD

**Issue by heartBall** [ozymandias547/snaptest#2]
Hi guys,
I'm using snaptest extension for Chrome and sometimes I have problem with performing a test. I press the "Run" button and it changes to "Running". Then I refresh the tab (like I always do) I'm using for tests to start testing and... nothing happens. I mean, the automatic test that I've created does not start, it does not even crash.
It happened to me twice - at the first time creating the test again helped, but I cannot make it every time this issue occures. Restarting does not help, neither for extension/browser, nor for pc.

The problem happens with only one of my tests, the rest works properly.

I know that the description is not very accurate, but I can help you to identify the problem if you tell me how. Or maybe I'm just doing something wrong, I'm new to the QA ;-)

heartBall

**Comment by ozymandias547** [comment]
This has been fixed. Let me know if it happens again.
