### ISSUE TITLE
Log file location for local testing

### ISSUE THREAD

**Issue by VR-Architect** [ozymandias547/snaptest#23]
Is there a way to see the test results when running nighwatch locally? I ran an npm test and all the steps show yellow and finished, but last line says there was an "npm ERR! Test failed. See above for more details" but there are no details.

Thanks

**Comment by ozymandias547** [comment]
NightwatchJS has a setting where the error reports go.  By default, it's a /reports folder in the root directory of the project.  If that doesn't exist, send me a screenshot of the failing test.
