### ISSUE TITLE
Clear cookies not working on localhost (Chrome Extension)

### ISSUE THREAD

**Issue by gbhojraj** [ozymandias547/snaptest#24]
I use clear cookies on the deployed site and it works, but when testing locally, using clear cookies with the parameter set to localhost, localhost:3000, http://localhost/, http://localhost:3000/, etc., the site's cookies aren't clearing.  

Is this a bug or am I doing something wrong, like using the wrong parameters?

**Comment by ozymandias547** [comment]
Try not adding the '/' at the end - it needs to be the raw protocal + domain.  use only:  http://localhost or http://localhost:3000 .

Let me know if that makes a difference.

**Comment by ozymandias547** [comment]
I'm going to add some validation to this action so it's easier.

**Comment by gbhojraj** [comment]
Thanks for the fast reply @ozymandias547 .  I've tried both of your suggestions, explicitly without the `/`, but in both cases the cookies were still present.  On the hosted website, Snaptest successfully clears cookies both with and without the `/`.

**Comment by gbhojraj** [comment]
Thanks. There are editable hosts files in Windows so I can try that.

**Comment by ozymandias547** [comment]
Fixed as of v0.5.8
