### ISSUE TITLE
Can't use component twice in same test

### ISSUE THREAD

**Issue by WilliamMayor** [ozymandias547/snaptest#25]
I see that setup and teardown are on the roadmap, fantastic!

In the meantime I thought I would have a "Sign Out" component that I used at the start and end of each test. Unfortunately this causes a loop. When the test finishes the second sign out component it jumps back up to the end of the first and starts the test again.

Thanks!

**Comment by ozymandias547** [comment]
Ah yea, I'm working on a fix for that now.  Thanks for letting me know - I believe it's only "aesthetic" right now, and actually runs properly despite the bad indication of where the test playback is.  

One thing I do to make sure I'm logged out before each test is to run the "Clear cookies" action on the ${baseUrl} at the very beginning of the test.   If you have more than just cookies keeping your user session, I'll be releasing a "clear caches" action which will give you the option to clear localstorage, sessionstorage, indexDB, and any others needed.

**Comment by ozymandias547** [comment]
Fixed as of v0.5.8
