### ISSUE TITLE
Description field: cursor jumps

### ISSUE THREAD

**Issue by sco2tbold** [ozymandias547/snaptest#28]
Hi. There's a annoyance with the description field: the cursor jumps to the first position of the input field while typing in the description field of a step. I'm not hitting <enter> in between; but even if hitting <enter> the cursor should stay at the position where it was before. Pls see the attached clip. 

 Thx.

[2017-10-02_13-52-271.zip](https://github.com/ozymandias547/snaptest/files/1348789/2017-10-02_13-52-271.zip)

**Comment by ozymandias547** [comment]
OK, i'll check that out.

**Comment by ozymandias547** [comment]
Will be fixed in v0.6.0 - please reopen if still found after that version.
