### ISSUE TITLE
Feature request: "Start over" button

### ISSUE THREAD

**Issue by sco2tbold** [ozymandias547/snaptest#29]
A "Clear all steps" resp. "Delete all" resp. "Start over" button would be great. 

![snag-02 10 2017-16 05 36](https://user-images.githubusercontent.com/7213039/31081369-f63abcaa-a78b-11e7-8554-27041ec31c61.png)

**Comment by ozymandias547** [comment]
Good idea - i'll put that in for the release on Friday.

**Comment by ozymandias547** [comment]
@sco2tbold 

Version v0.5.8 will have a "select all" button, which you can use in conjunction with the delete button to easily start over.  It will regenerate the baseUrl properly each time... but the only thing that isn't "cleared" will be the custom variables and the test name/description manually added to a test.  Let me know if you'd like a more "all-encompasing" reset button, and i can get that in as well.  It'll need to be "buried" a little deeper in the test details section.

**Comment by sco2tbold** [comment]
That's awesome. Thanks for the quick reaction and changes.

No, I was thinking of a "clear all" of the test steps. So the "check all" and "delete" combination is good.
