### ISSUE TITLE
Feature request: drag and drop for test actions

### ISSUE THREAD

**Issue by sco2tbold** [ozymandias547/snaptest#37]
I was surprised to find that I cannot change the order of test steps at all? When creating tests manually then this is indispensable. 

Would be great minor extension. Maybe with drag-n-drop like the folders and tests.

**Comment by ozymandias547** [comment]
Hi @sco2tbold - it's not as obvious as it once was, but you can definitely re-order test steps.  Select the action you want to reorder, and use the following button:

<img width="424" alt="screen shot 2017-11-17 at 11 28 46 pm" src="https://user-images.githubusercontent.com/2013007/32954812-c7564ffa-cb79-11e7-9573-41f67dbc1ba6.png">

**Comment by ozymandias547** [comment]
Oh and about drag-and-drop - that will be a nice feature.  We'll put that on the map.

**Comment by ozymandias547** [comment]
@sco2tbold We just added this feature in v1.1.0 -  Thanks for letting us know you wanted it.
