### ISSUE TITLE
Nightwatch: hash is missing for IDs?

### ISSUE THREAD

**Issue by sco2tbold** [ozymandias547/snaptest#39]
I expected the selector ID render it with the hash sign? Pls see the attached screenshot. 
![snag-20 11 2017-12 14 41](https://user-images.githubusercontent.com/7213039/33015886-aa750550-cdec-11e7-8a98-8866aa5be4d8.png)

**Comment by ozymandias547** [comment]
@sco2tbold Please upgrade to the latest version of the snaptest-cli.  Its currently at 1.3.4, so you can use `npm install -g snaptest-cli@1.3.4`

**Comment by sco2tbold** [comment]
That's it. Thanks!
