### ISSUE TITLE
Question: Assert value of element and do caclulations

### ISSUE THREAD

**Issue by sco2tbold** [ozymandias547/snaptest#40]
Is it possible to do calculations with "dynamic variables"? 

Example: 

- I want to save the count of items in a test step; 
- then create a new item and 
- finally assert if the count was raised by one

Like: toString(parseInt(${PatientCount}+1))

![image](https://user-images.githubusercontent.com/7213039/33020510-f32090d2-cdfe-11e7-9289-5bc37dff604b.png)

**Comment by ozymandias547** [comment]
@sco2tbold We'll look into this - it may be an easy addition to allow an evaluation like this.

**Comment by ozymandias547** [comment]
@sco2tbold We've finished this in version 1.20.0 - you may now use $(1+1) etc to evaluate. Variables are read only by using:

$(vars.baseUrl)

and you may set dynamic variables (which override the normal variable heirarchy using:

$(exports.baseUrl="anything")

You can do multiple evals like this:

$("hello") world $("!")

And it can execute random javascript:

$(Math.random() + "")
