### ISSUE TITLE
Bug: The Description on tests are not saving.

### ISSUE THREAD

**Issue by sethdiehm** [ozymandias547/snaptest#41]
Whenever I restart my computer the information that I put into the tests description is gone.

**Comment by ozymandias547** [comment]
@sethdiehm are you using private mode or cloud mode?

**Comment by sethdiehm** [comment]
I am using the cloud mode. Also it happens whenever I logout/in of my account in the chrome extension.

**Comment by ozymandias547** [comment]
This has been fixed.  Please reopen if seeing similar behavior.
