### ISSUE TITLE
Test runs and results page on site blank

### ISSUE THREAD

**Issue by saca-puntas** [ozymandias547/snaptest#49]
https://www.snaptest.io/doc/test-runs-and-results shows no info on desktop or mobile.
![image](https://user-images.githubusercontent.com/38920933/39538091-3fae0a7e-4e01-11e8-9463-e126c7f83b8f.png)

**Comment by ozymandias547** [comment]
Thank you for letting us know.  We'll get this fixed up asap.

**Comment by ozymandias547** [comment]
This has been fixed. Please find result help info at [https://www.snaptest.io/doc/runs](https://www.snaptest.io/doc/runs)
