### ISSUE TITLE
Template string {random} doesn´t work when breakpoint is set 

### ISSUE THREAD

**Issue by veronikaba** [ozymandias547/snaptest#7]
For a registration formular I have set two email variables in a component. They are identically like this: bla{random1}@foo.de because you need to validate the exact email by filling it in twice. When I set breakpoints at Change input to {email} and Change input to {email2} the random1 number in both email variables will not be the same. If I don´t set the breakpoints they are the same and everything works fine.

**Comment by ozymandias547** [comment]
Thanks for the report - I'll look into it.

**Comment by ozymandias547** [comment]
@veronikaba Fixed and will be in release 0.4.9 .
