### ISSUE TITLE
The button for editing folder names isn't working.

### ISSUE THREAD

**Issue by lucasbendasantos** [ozymandias547/snaptest#9]
I tried to edit the name of a folder, but it does the "DRAG AND DROP" to organize ...
Another suggestion for future versions is to create an auto-incremental variable for looping tests, if you already have it, I could not locate ...
thank you!

**Comment by brunolucena** [comment]
Same problem here. It only happens when you first create a folder. Then you have to close SnapTest and open it again so you can rename it.

**Comment by ozymandias547** [comment]
I keep hearing about this issue, but am unable to easily reproduce.  This extra information helps - I'll try to fix it again.

**Comment by ozymandias547** [comment]
Found and fixed this issue - it will be in v0.5.8.

@lucasbendasantos p.s. - flow control with auto implement won't be long.
